/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DeviceTestRouteImport } from './routes/device-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItineraryIdRouteImport } from './routes/itinerary.$id'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceTestRoute = DeviceTestRouteImport.update({
  id: '/device-test',
  path: '/device-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIdRoute = ItineraryIdRouteImport.update({
  id: '/itinerary/$id',
  path: '/itinerary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/device-test': typeof DeviceTestRoute
  '/gallery': typeof GalleryRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/device-test': typeof DeviceTestRoute
  '/gallery': typeof GalleryRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/device-test': typeof DeviceTestRoute
  '/gallery': typeof GalleryRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/device-test' | '/gallery' | '/itinerary/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/device-test' | '/gallery' | '/itinerary/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/device-test'
    | '/gallery'
    | '/itinerary/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DeviceTestRoute: typeof DeviceTestRoute
  GalleryRoute: typeof GalleryRoute
  ItineraryIdRoute: typeof ItineraryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-test': {
      id: '/device-test'
      path: '/device-test'
      fullPath: '/device-test'
      preLoaderRoute: typeof DeviceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$id': {
      id: '/itinerary/$id'
      path: '/itinerary/$id'
      fullPath: '/itinerary/$id'
      preLoaderRoute: typeof ItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DeviceTestRoute: DeviceTestRoute,
  GalleryRoute: GalleryRoute,
  ItineraryIdRoute: ItineraryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
